name: Upload S3
description: 'Upload directory to S3'
author: 'Dong Keon Kim'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  s3_key_id:
    description: 's3 key id'
    required: true
  s3_secret_access_key:
    description: 's3 secret access key'
    required: true
  s3_bucket:
    description: 's3 bucket name'
    required: true
  s3_region:
    description: 's3 region'
    required: true
  s3_host:
    description: 's3 host/provider'
    required: false
  source_dir:
    required: true
    description: 'directory to upload'
  destination_dir:
    required: true
    description: 'directory upload destination'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node12'
  main: 'dist/index.js'
